# name of workflow
name: Android Build Pipeline

# define on witch Github event, workflow will trigger
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up jdk 20
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: '20'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: create local.properties from secret variables
        run: echo BACKEND_URL=${{ secrets.BACKEND_URL }} > ./local.properties

      # KtLint
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck

      - name: archive ktLint reports on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: code_linting
          path: "**/build/reports/ktlint/**/*.html"
